### ISSUE TITLE
Header: Shouldn't we add Farm hours and Contact hours in the header section as per 10-JOO-Areas Serviced design?

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Joondalup-Turf-Farm#64]
![image](https://cloud.githubusercontent.com/assets/11186313/16375189/c9a3bb3a-3c8c-11e6-827c-d8efcab8fcf9.png)

**Comment by charmander-titan** [comment]
Ms Selie, sir berns said we will follow the header design which does not have the farm hours and contact hours.
